#!/bin/sh

set -ex

# CIS Benchmarking
chmod 0444 /etc/login.defs
sed -i -e "s/^PASS_MAX_DAYS\s\+99999/PASS_MAX_DAYS   60/" /etc/login.defs
sed -i -e "s/^PASS_MIN_DAYS\s\+0/PASS_MIN_DAYS  7/" /etc/login.defs
sed -i -e "s/^UMASK\s\+022/UMASK        027/" /etc/login.defs

chmod 0640 /etc/shadow
